### ISSUE TITLE
Input data shape for `DTCWT`

### ISSUE THREAD

**Issue by xir4n** [kymatio/murenn#39]
Now that `DTCWT` requires the input data to be a tensor of shape `(B, C, 2**J)`, where J is the number of wavelet scales, it can be inconvenient to apply to real data. However, the [dtcwt.np](https://github.com/rjw57/dtcwt/tree/master/dtcwt/numpy) package offers a less strict requirement for the input shape. Instead of `(B, C, 2**J)`, it only requires the input length to be even. To accommodate this, I made some modifications to achieve the same results.

**Comment by xir4n** [comment]
Thanks @lostanlen , I realized it's better to make `DTCWT` support both even and odd input length considering the implications for `MuReNNDirect`

**Comment by xir4n** [comment]
> Perhaps we could have something like that too?
Thanks for your suggestions, this is totally possible. But in my opinion, implementing it will require some effort, and I think it's not that urgent at the moment. Would it be acceptable for me to draft a new issue and address it in the future?

**Comment by lostanlen** [comment]
You're right, let's put it as 0.4 milestone, not 0.3
