### ISSUE TITLE
`MuReNNDirect.to_conv1d()`

### ISSUE THREAD

**Issue by lostanlen** [kymatio/murenn#45]
I suggest we have a method in `MuReNNDirect` that would compute the single-resolution equivalent impulse response of the MuReNN layer. This would be helpful for visualization in Fourier domain, for receptive fields, and for comparing computational costs.

The `to_conv1d` method should return a complex-valued PyTorch tensor of shape `(Q*J, (2**J)*T)`. It would involve IDTCWT. This can be done efficiently by introducing an object `@property` which would be computed on demand.

```
   DTCWT        conv1d        IDTCWT
δ -------> ψ_j --------> w_j -------> y_j
```

I volunteer to do this.

**Comment by xir4n** [comment]
I volunteer to do this!
