### ISSUE TITLE
MuReNNDirect downsampling issue

### ISSUE THREAD

**Issue by xir4n** [kymatio/murenn#59]
The downsampling operation in `MuReNNDirect` returns the low-pass output of the dual-tree complex wavelet transform, which interleaves the real and imaginary parts of a complex signal. This may introduce aliasing and destroy the shift-invariance property of the transform. 

Some modifications to the downsampling process are needed to fix this issue. Potential solutions include:

1. Using only the real part of the downsampled signal.
2. Applying another modulus operation.
3. Using a another low-pass filter (which one to use?).

**Comment by lostanlen** [comment]
thank you for raising this issue

my suggestion is, following (3), to replace the current complex low-pass filter by its real part
and to (optionally) apply a ReLU to guarantee nonnegativity of the output

**Comment by lostanlen** [comment]
closed by #60
