### ISSUE TITLE
Bug in `MuReNNDirect.to_conv1d `

### ISSUE THREAD

**Issue by xir4n** [kymatio/murenn#64]
There is a bug when getting murenn the filters. (ref: [Matlab official documentation](https://fr.mathworks.com/help/wavelet/ug/analytic-wavelets-using-the-dual-tree-wavelet-transform.html))

Here's an explanation thanks to @lostanlen 
Given the frame analysis operation:
$y[k]=\Psi x[k]=<x|\Psi_k>$,
and the frame synthesis operation:
$\Psi^* y=<y|\Psi^*>=\sum y[k]\Psi_k$,
the synthesis operator satisfies
$<\Psi^*a|x>=<a|\Psi x>=<a|y>$
for all $a$ in the DTCWT coefficient space.
Thus, setting $a=\delta_j\ast w_j$ helps to visualize the filters. 

If there are any inaccuracies in this explanation, please feel free to correct them.

**Comment by lostanlen** [comment]
Closed by #62
